driver = pgsql
connect = host=/run/postgresql dbname=mailserver user=user password=password

password_query = SELECT password FROM dovecot_users WHERE username = '%u'
user_query = SELECT home, mail_location as mail, uid, gid, quota_rule FROM dovecot_users WHERE username = '%u'

iterate_query = SELECT username as user FROM dovecot_users
