# documentation: https://rspamd.com/doc/modules/dkim_signing.html

enabled = false;

sign_authenticated = true;
sign_local = true;
try_fallback = true;

use_domain = "header";
use_redis = false; # don't change unless Redis also provides the DKIM keys
use_esld = true;
allow_username_mismatch = true; #SPOOF_PROTECTION is done by Postfix?

# you want to use this in the beginning
check_pubkey = true;
allow_pubkey_mismatch = false;

#selector = "mail";
# The path location is searched for a DKIM key with these variables:
# - `$domain` is sourced from the MIME mail message `From` header
# - `$selector` is configured for `mail` (as a default fallback)
#path = "/tmp/docker-mailserver/rspamd/dkim/$domain/$selector.private";

domain {
    c0d3m4513r.com {
        path = "/tmp/docker-mailserver/rspamd/dkim/c0d3m4513r.com/mail.private";
        selector = "mail";
    }
    meandtheboys.eu {
        path = "/tmp/docker-mailserver/rspamd/dkim/meandtheboys.eu/mail.private";
        selector = "mail";
    }
    whitewelpe.de {
        path = "/tmp/docker-mailserver/rspamd/dkim/whitewelpe.de/mail.private";
        selector = "mail";
    }
}

